services:
  _defaults:
    # no autowire as its inside a bundle
    autowire: false
    autoconfigure: false

  Floatingbits\EvolutionaryAlgorithmBundle\Controller\ProblemController:
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]


  Floatingbits\EvolutionaryAlgorithmBundle\Repository\ProblemRepository:
    autowire: true
    tags: ['doctrine.repository_service']

  Floatingbits\EvolutionaryAlgorithmBundle\Controller\ProblemInstanceController:
    arguments: ['@event_dispatcher']
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]


  Floatingbits\EvolutionaryAlgorithmBundle\Repository\ProblemInstanceRepository:
    autowire: true
    tags: [ 'doctrine.repository_service' ]

  Floatingbits\EvolutionaryAlgorithmBundle\Controller\TournamentTypeController:
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]


  Floatingbits\EvolutionaryAlgorithmBundle\Repository\TournamentTypeRepository:
    autowire: true
    tags: [ 'doctrine.repository_service' ]

  Floatingbits\EvolutionaryAlgorithmBundle\Controller\TournamentConfigurationController:
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]


  Floatingbits\EvolutionaryAlgorithmBundle\Repository\TournamentConfigurationRepository:
    autowire: true
    tags: [ 'doctrine.repository_service' ]


  Floatingbits\EvolutionaryAlgorithmBundle\Controller\TournamentRunController:
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

  Floatingbits\EvolutionaryAlgorithmBundle\Repository\TournamentRunRepository:
    autowire: true
    tags: [ 'doctrine.repository_service' ]

  Floatingbits\EvolutionaryAlgorithmBundle\Theming\TemplateProvider:
    arguments: [[], '@twig']

  ea.theme.default:
    class: Floatingbits\EvolutionaryAlgorithmBundle\Theming\Theme
    arguments: ['@@EvolutionaryAlgorithm/_includes/ea_themes/default']
    tags: [ 'evolutionary_algorithm.theme' ]

  Floatingbits\EvolutionaryAlgorithmBundle\Problem\ExampleProblemProvider:
    tags: [ 'evolutionary_algorithm.problem_provider' ]


  Floatingbits\EvolutionaryAlgorithmBundle\Evolution\Provider\DefaultTournamentProvider:
    tags: [ 'evolutionary_algorithm.tournament_provider' ]

  Floatingbits\EvolutionaryAlgorithmBundle\Command\SyncProblemsCommand:
    arguments: ['@Floatingbits\EvolutionaryAlgorithmBundle\Repository\ProblemRepository']
    tags:
      - { name: 'console.command', command: 'evolutionary-algorithm:sync-problems' }

  Floatingbits\EvolutionaryAlgorithmBundle\Command\SyncTournamentTypesCommand:
    arguments: [ '@Floatingbits\EvolutionaryAlgorithmBundle\Repository\TournamentTypeRepository' ]
    tags:
      - { name: 'console.command', command: 'evolutionary-algorithm:sync-tournament-types' }

  Floatingbits\EvolutionaryAlgorithmBundle\Evolution\TournamentRunner:
    arguments: []